# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "python_demo"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"

  config.vm.forward_port 80, 80
  config.vm.forward_port 9090, 9090
  config.vm.forward_port 22, 2224

  config.vm.share_folder "python_demo", "/srv/python_demo", "../"
end
